service: aws-lambda-xmen-mutant-checker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: leonidas
  region: sa-east-1
  environment:
    TableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:693620351674:table/${self:custom.tableName}

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-scripts

custom:
  tableName: DnaTableCircleCi
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  scripts:
    hooks:
      'aws:common:validate:validate': npm run test

functions:
  checkDna:
    handler: lambdas/endpoints/checkDna.handler
    events:
      - httpApi:
          path: /mutant
          method: post
  getStats:
    handler: lambdas/endpoints/getStats.handler
    events:
      - httpApi:
          path: /stats
          method: get

resources:
  Resources:
    dnaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
