service: aws-lambda-xmen-mutant-checker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:693620351674:table/DnaTable

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  checkDna:
    handler: src/checkDna.saveDnaChain
    events:
      - httpApi:
          path: /mutant
          method: post
  getStats:
    handler: src/getStats.getStats
    events:
      - httpApi:
          path: /stats
          method: get

resources:
  Resources:
    dnaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DnaTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
