version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          command: sudo npm i -g serverless npm@latest
      - run:
          command: npm install
      - run:
          command: chmod +x ./.circleci/install-credentials.sh 
      - run:
          command: ./.circleci/install-credentials.sh
      - run:
          command: sls deploy
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context: serverlessMutantCheckerProject
